### PR TITLE
Updating to official speedtest-cli

### PR DESCRIPTION
**Pull request by dnagl**
# Resolves
* #36 - Possibility of updating to use official Speedtest CLI?

# Changes
* Renamed `speedtest.py` to `speedtestRunner.py`
  * [IMPORTANT] this change is needed to import the official speedtest-cli python package 'speedtest'
* Migrated to `speedtest` package

### CODE REVIEW

**Comment by roest01** [comment]
🤩

**Comment by dnagl** [comment]
@roest01 Please have a look at the request and let me know if there should be something changed :)

**Comment by Jiriteach** [comment]
Awesome work - been meaning to get around to sorting this but just been too busy! Keen to test things soon.

**Comment by Jiriteach** [comment]
@dnagl - I had a quick look at your changes to test things out.

> from speedtest import Speedtest

Is importing pip install speedtest-cli which is not the official Speedtest.net speedtest-cli? Its the same one thats already used in this package from here - https://pypi.org/project/speedtest-cli/ from sivel.

Can you confirm this is correct? Also built it and ran - wasnt able to get it to run but I havent looked into it yet.

Thanks

**Comment by dnagl** [comment]
@Jiriteach .... my bad .... i thought this cli would be the original one. I had a look on the speedtest.net page and found out that I had no idea that there was another package out there.
I'll fix my stuff and "migrate" to the now really original cli ^^

thanks for finding the mistake

**Comment by Jiriteach** [comment]
@dnagl - Let us know how you get on. Will be a bit more of a challenge since there is no Python wrapper for the official speedtest-cli. Also it’s run in quite of a different way. It does output to CSV but in a different structure. 

I’ve managed to get it scripted via Python. Just haven’t had the time to add it to Docker.

**Comment by 19wolf** [comment]
Is there any movement on this? I've found that speedtest-cli records my speeds as 20-60% lower than the offical binary from ookla...

**Comment by Jiriteach** [comment]
@roest01 - the merged commit into master does not update it to use the official cli. I mentioned this above to @dnagl.

**Pull request merged**
